### ISSUE TITLE
Deamon feature not working for me

### ISSUE THREAD

**Issue by All498098** [c22dev/Geranium#2]
On iOS 16.2 iPhone 14PM I go to disable some Deamons and it’ll prompt me which is fine I agree then when I reboot I check to see if it worked by going to OTA tab and the OTA is working but shouldn’t be.
I check to see the disabled Deamons and it’s two random ones I never disabled one “bootps” and one other one but the ones I choose specifically got reenabled ( I know this because I used iCleaner years back to turn off OTA ) I just went to turn off an extra deamon and it reset back to one’s I never touched.

also pressing reboot maybe it’s just a user space reboot as it didn’t fully reboot ( Face ID worked on boot ) shouldn’t have worked

**Comment by c22dev** [comment]
Hi there !

Those you never disabled are Apple iOS defaults. As said in the footer, don't change those you didn't change. Can you screen record disabling software update daemon and looking on manager ?

**Comment by All498098** [comment]
Yes back when I used iCleaner pro I had OTA disabled I went to disable some Wi-Fi analytics deamon and it just reverted the old changes but one moment.-JeffOn Jan 14, 2024, at 3:17 PM, c22dev ***@***.***> wrote:﻿
Hi there !
Those you never disabled are Apple iOS defaults. As said in the footer, don't change those you didn't change. Can you screen record disabling software update daemon and looking on manager ?

**Comment by All498098** [comment]
Doesn’t matter what I disable it’s always these two on the list -JeffOn Jan 14, 2024, at 3:33 PM, Jeffery Allen ***@***.***> wrote:﻿Yes back when I used iCleaner pro I had OTA disabled I went to disable some Wi-Fi analytics deamon and it just reverted the old changes but one moment.-JeffOn Jan 14, 2024, at 3:17 PM, c22dev ***@***.***> wrote:﻿
Hi there !
Those you never disabled are Apple iOS defaults. As said in the footer, don't change those you didn't change. Can you screen record disabling software update daemon and looking on manager ?

**Comment by c22dev** [comment]
I tested again with one of my testers and my device (@Spygamer10) and it also works on his/my side. You might wanna hit the Reset button in the manager, your old daemon manager might have caused issues with the plist. Also, before doing that, can you send me the file in `/var/db/com.apple.xpc.launchd/disabled.plist` please ?

**Comment by All498098** [comment]
Yes one moment.-JeffOn Jan 14, 2024, at 4:39 PM, c22dev ***@***.***> wrote:﻿
I tested again with one of my testers and my device ***@***.***) and it also works on his/my side. You might wanna hit the Reset button in the manager, your old daemon manager might have caused issues with the plist. Also, before doing that, can you send me the file in /var/db/com.apple.xpc.launchd/disabled.plist please ?

**Comment by All498098** [comment]
This has both disabled and some migrated file -JeffOn Jan 14, 2024, at 5:47 PM, Jeffery Allen ***@***.***> wrote:﻿Yes one moment.-JeffOn Jan 14, 2024, at 4:39 PM, c22dev ***@***.***> wrote:﻿
I tested again with one of my testers and my device ***@***.***) and it also works on his/my side. You might wanna hit the Reset button in the manager, your old daemon manager might have caused issues with the plist. Also, before doing that, can you send me the file in /var/db/com.apple.xpc.launchd/disabled.plist please ?

**Comment by c22dev** [comment]
I am not sure I understood what you meant. Try resetting the file from the manager and rebooting your device as said in the app.

**Comment by WardOps** [comment]
The reboot button after disabling daemons is the problem, manually rebooting using the power button worked and the daemons that i disabled, now appeared on the list.

**Comment by c22dev** [comment]
Will remove that OR kill launchd as root. Thanks a lot.

**Comment by c22dev** [comment]
Fixed in [Release 1.0.4](https://github.com/c22dev/Geranium/releases/tag/1.0.4)

**Comment by yourmotheriskoi** [comment]
Not fixed in 1.0.4. I see daemons being changed and listed upon reboot but when I check for a software update on my A11 iOS 16.5 iP8+ I am able to get a successful ping for a software update. When I go back to Geranium, never closed it from background, and i see my OTA daemon and Software update daemons suddenly disappear from the list.

Maybe it's because I used iCleaner in the past and disabled my OTA daemons that way?

Here's what fixed for me so far.
1. Use Filza delete the "Geranium" folder from /var/mobile/Containers/Data/Application and from /var/containers/Bundle/Application
2. Navigate to /var/db/com.apple.xpc.launchd and delete the files in there, it should only be your disabled.plist and disabled.migrated
3. Delete Geranium via trollstore, this kept the icon on my homescreen so delete the icon now.
4. If you have a backup of your disabled.plist, that you know was working before using this software, load it in and do your reboot, verify that your OTA updates are successfully blocked. If you don't have a backup file then continue to the next step
5. Reboot your device and let it generate a new disabled.plist, it should be 30 exact entries long. Use filza and manually add the daemons you wish to disable. Don't forget that daemons ARE case sensitive!
6. Final reboot and verify a successful OTA block.

**Comment by All498098** [comment]
1.0.4 doesn’t seem to want to do any applying where as last time it showd something being applied now it’s just blank even with the manual reboot -JeffOn Jan 14, 2024, at 9:29 PM, yourmotheriskoi ***@***.***> wrote:﻿
Not fixed in 1.0.4. I see daemons being changed and listed upon reboot but when I check for a software update on my A11 iOS 16.5 iP8+ I am able to get a successful ping for a software update. When I go back to Geranium, never closed it from background, and i see my OTA daemon and Software update daemons suddenly disappear from the list.
Maybe it's because I used iCleaner in the past and disabled my OTA daemons that way?
Here's what fixed for me so far.

Use Filza delete the "Geranium" folder from /var/mobile/Containers/Data/Application and from /var/containers/Bundle/Application
Navigate to /var/db/com.apple.xpc.launchd and delete the files in there, it should only be your disabled.plist and disabled.migrated
Delete Geranium via trollstore, this kept the icon on my homescreen so delete the icon now.
If you have a backup of your disabled.plist, that you know was working before using this software, load it in and do your reboot, verify that your OTA updates are successfully blocked. If you don't have a backup file then continue to the next step
Reboot your device and let it generate a new disabled.plist, it should be 30 exact entries long. Use filza and manually add the daemons you wish to disable. Don't forget that daemons ARE case sensitive!
Final reboot and verify a successful OTA block.

**Comment by c22dev** [comment]
Try 1.1
